site_name: Miineidi Docs
nav:
    - Home: index.md
    - Use cases: use case.md
generator: false
theme:
    features:
        - navigation.sections
    logo: assets/icon.svg
    favicon: assets/icon.svg
    name: material
    palette:
        primary: teal

extra:
    social:
      - icon: fontawesome/brands/github
        link: https://miineidi.surge.sh/
    
copyright: Copyright 2019-2021 Miineidi with love by lordvins226
              