site_name: Miineidi Docs

theme:
    logo: assets/icon.svg
    favicon: assets/icon.svg
    name: material
    palette:
        primary: teal

extra:
    generator: false
    social:
      - icon: fontawesome/brands/github
        link: https://miineidi.surge.sh/
    
copyright: Copyright &copy; 2019 - 2021 Miineidi
              